version: '2'

services:
  postgresql:
    image: ddoyle/postgresql:9.3_bpmsuite
    ports:
      - "5432"
  jbossBpmsuite:
    image: ddoyle/jboss-bpmsuite:6.2.0_postgresql
    volumes:
      - jboss-bpmsuite-6.2.0_postgresql-data:/bpms-data
    links:
      - postgresql:postgresql
    ports:
      - "8080"
      - "9990"
      - "9999"

volumes:
   jboss-bpmsuite-6.2.0_postgresql-data: {}

